[package]
name = "shelf"
version = "0.0.1"
edition = "2021"
description = "Your personal CLI bookshelf for storing and recalling useful commands."
categories = ["cli", "shell"]

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
toml = "=0.8.19"
anyhow = "1.0"
dirs = "5.0"
colored = "2"
