[package]
name = "shelf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
toml = "=0.8.19"
anyhow = "1.0"
dirs = "5.0"
